### PR TITLE
[hotfix] fix build of lib/Testing

### PR DESCRIPTION
**Pull request by tlepley-cadence**
*Description*: 
Fix broken build due to #2132 .
Since `Testing` is in `lib/` and `gtest` in `tests`, cmake doesn't seem to properly 'connect' both. Declaring the `gtest` includes at top level like it is already done for `fp16` solves the build issue.
```
glow/lib/Testing/StrCheck.cpp:18:25: fatal error: gtest/gtest.h: No such file or directory
 #include "gtest/gtest.h"
                         ^
compilation terminated.
```

*Testing*: Builds correctly locally

*Documentation*: N/A

### CODE REVIEW

**Comment by stoklund** [comment]
Would it be better to move the Testing directory into tests?

**Comment by tlepley-cadence** [comment]
I cancel this fix PR that should be solved by #2141
